### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by vesche** [vesche/elbb#1]
Assorted todo list:
* [x] Make bot headless via xvfb
* [x] Update elbb deployment script to preserve iptables
* [x] Auto login
* [x] Remote image screenshot and cropping utility
* [x] Retake all images for headless
* [x] Replace screenshot in pyautogui with mss for speedup
* [x] Move elbb / setup.py to `bot/` (update deploy)
* [ ] Use [this](https://stackoverflow.com/a/54794506/4396927) for pyscreeze fork in setup.py, update deploy
* [x] elbb should have a systemd service file that deployment drops, starts, and enables
* [ ] Swap out filelock for redis in elbb.queue
* [x] frontend: needs a home button to return to bot selection screen
* [x] frontend: should have a class or dictionary that stores websocket connects
* [x] Improve code for playbook selection, arguments, starting, changing playbooks, etc
* [ ] Swap back and forth between bots without websocket disconnect
* [ ] Handle websocket disconnects better (client & server)
* [ ] Frontend sidebar with playbooks
* [ ] Fix "message" GET request to be async in frontend (non-periodic)
* [ ] Button to stop / disconnect
* [ ] elbb: playbook / ability to move between maps
* [ ] elbb: Ability to OCR map coordinates and move to specified coordinates
* [ ] elbb: resources & pictures for: all UI, all storage, map signatures, important items, etc
* [ ] elbb: playbook ideas- auto cotton, auto sulfur harvest
* [ ] Fix get book status for new dimensions
* [ ] Fix get manu for new dimensions
* [ ] Experiment with color picking
* [ ] Experiment with read-only VNC in-browser via guacamole or noVNC
* [ ] Experiment with js graphs/charts for stat reporting
* [ ] Deployment script for frontend
* [ ] Create a drawio picture to show all the tech in play
